variables:
  CUSTOMER: "asa-info"
  PLUGIN_NAME: "perimetre_asa"
  PROJECT_ID: "334"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages:
- tests 🎳

flake8:
  stage: tests 🎳
  script:
    - make flake8
  tags:
    - factory

qgis-3.4:
  stage: tests 🎳
  before_script:
    - >
      docker run
      -d --name ${CI_JOB_ID}
      -v ${CI_PROJECT_DIR}/${PLUGIN_NAME}:/${PLUGIN_NAME}
      -e GITLAB=yes -e DISPLAY=:99
      qgis/qgis:release-3_4
    - sleep 10
    - docker exec -t ${CI_JOB_ID} sh -c "qgis_setup.sh ${PLUGIN_NAME}"
  script:
    - >
      docker exec -t ${CI_JOB_ID}
      sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.qgis_plugin_tools.infrastructure.test_runner.test_package"
  after_script:
    - docker rm -f ${CI_JOB_ID}
  tags:
    - factory
